import "@/app/globals.css";


export const metadata = {
    title: "Projects | Flowzy",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (

        <div>
            {children}
        </div>

    );
}
