import "@/app/globals.css";

export const metadata = {
    title: "Dashboard | Flowzy",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (

        <div
            className={`flex`}
        >

            <main className="flex-1 p-6 bg-gray-50 ">
                {children}
            </main>


        </div>

    );
}
