import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import SideBar from "@/components/organisms/SideBar";

export const metadata = {
    title: "Dashboard | Flowzy",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (

        <div
            className={`flex`}
        >

            <SideBar />

            <main className="flex-1 bg-gray-50 min-h-screen">
                {children}
            </main>


        </div>

    );
}
